In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
loan15 = pd.read_csv('LoanStats3d.csv', skipinitialspace=True, header=1
                    )

c:\users\greg\appdata\local\programs\python\python36\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
loan15.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,68009401,72868139.0,16000.0,16000.0,16000.0,60 months,14.85%,379.39,C,C5,...,0.0,2.0,78.9,0.0,0.0,2.0,298100.0,31329.0,281300.0,13400.0
1,68354783,73244544.0,9600.0,9600.0,9600.0,36 months,7.49%,298.58,A,A4,...,0.0,2.0,100.0,66.7,0.0,0.0,88635.0,55387.0,12500.0,75635.0
2,68466916,73356753.0,25000.0,25000.0,25000.0,36 months,7.49%,777.55,A,A4,...,0.0,0.0,100.0,20.0,0.0,0.0,373572.0,68056.0,38400.0,82117.0
3,68466961,73356799.0,28000.0,28000.0,28000.0,36 months,6.49%,858.05,A,A2,...,0.0,0.0,91.7,22.2,0.0,0.0,304003.0,74920.0,41500.0,42503.0
4,68495092,73384866.0,8650.0,8650.0,8650.0,36 months,19.89%,320.99,E,E3,...,0.0,12.0,100.0,50.0,1.0,0.0,38998.0,18926.0,2750.0,18248.0

In [7]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_sccore

rfc = ensemble.RandomForestClassifier()
X = loan15.drop('loan_status', 1)
Y = loan15['loan_status']
X = pd.get_dummies(X)

print(cross_val_score(rfc, X, Y, cv=5))

ImportError: cannot import name 'cross_val_sccore'

In [8]:
categorical = loan15.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

id
421097
term
2
int_rate
110
grade
7
sub_grade
35
emp_title
120812
emp_length
11
home_ownership
4
verification_status
3
issue_d
12
loan_status
7
pymnt_plan
1
url
421095
desc
34
purpose
14
title
27
zip_code
914
addr_state
49
earliest_cr_line
668
revol_util
1211
initial_list_status
2
last_pymnt_d
25
next_pymnt_d
4
last_credit_pull_d
26
application_type
2
verification_status_joint
3

In [9]:
# Convert ID and Interest Rate to numeric.
loan15['id'] = pd.to_numeric(loan15['id'], errors='coerce')
loan15['int_rate'] = pd.to_numeric(loan15['int_rate'].str.strip('%'), errors='coerce')

# Drop other columns with many unique variables
loan15.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'addr_state', 'desc'], 1, inplace=True)

In [10]:
loan15 = loan15[:-2]

In [11]:
pd.get_dummies(loan15)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,...,last_credit_pull_d_Nov-2016,last_credit_pull_d_Oct-2015,last_credit_pull_d_Oct-2016,last_credit_pull_d_Sep-2015,last_credit_pull_d_Sep-2016,application_type_INDIVIDUAL,application_type_JOINT,verification_status_joint_Not Verified,verification_status_joint_Source Verified,verification_status_joint_Verified
0,68009401.0,72868139.0,16000.0,16000.0,16000.0,14.85,379.39,48000.0,33.18,0.0,...,0,0,0,0,0,1,0,0,0,0
1,68354783.0,73244544.0,9600.0,9600.0,9600.0,7.49,298.58,60000.0,22.44,0.0,...,0,0,0,0,0,1,0,0,0,0
2,68466916.0,73356753.0,25000.0,25000.0,25000.0,7.49,777.55,109000.0,26.02,0.0,...,0,0,0,0,0,1,0,0,0,0
3,68466961.0,73356799.0,28000.0,28000.0,28000.0,6.49,858.05,92000.0,21.60,0.0,...,0,0,0,0,0,1,0,0,0,0
4,68495092.0,73384866.0,8650.0,8650.0,8650.0,19.89,320.99,55000.0,25.49,0.0,...,0,0,0,0,0,1,0,0,0,0
5,68506798.0,73396623.0,23000.0,23000.0,23000.0,8.49,471.77,64000.0,18.28,0.0,...,0,0,0,0,0,1,0,0,0,0
6,68566886.0,73456723.0,29900.0,29900.0,29900.0,12.88,678.49,65000.0,21.77,0.0,...,0,0,0,0,0,1,0,0,0,0
7,68577849.0,73467703.0,18000.0,18000.0,18000.0,11.99,400.31,112000.0,8.68,0.0,...,0,0,0,0,0,1,0,0,0,0
8,66310712.0,71035433.0,35000.0,35000.0,35000.0,14.85,829.90,110000.0,17.06,0.0,...,0,0,0,0,0,1,0,0,0,0
9,68476807.0,73366655.0,10400.0,10400.0,10400.0,22.45,289.91,104433.0,25.37,1.0,...,0,0,0,0,0,1,0,0,0,0
10,68341763.0,72928789.0,20000.0,20000.0,20000.0,10.78,432.66,63000.0,10.78,0.0,...,0,0,0,0,0,0,1,1,0,0
11,68356421.0,73246236.0,22400.0,22400.0,22400.0,12.88,508.30,95000.0,22.98,0.0,...,0,0,0,0,0,1,0,0,0,0
12,68426545.0,73316365.0,16000.0,16000.0,16000.0,12.88,363.07,70000.0,26.40,0.0,...,0,0,0,0,0,1,0,0,0,0
13,68407277.0,73297111.0,3600.0,3600.0,3600.0,13.99,123.03,55000.0,5.91,0.0,...,0,0,0,0,0,1,0,0,0,0
14,68355089.0,73244858.0,24700.0,24700.0,24700.0,11.99,820.28,65000.0,16.06,1.0,...,0,0,0,0,0,1,0,0,0,0
15,68466926.0,73356763.0,10000.0,10000.0,10000.0,6.49,306.45,85000.0,13.07,0.0,...,0,0,0,0,0,1,0,0,0,0
16,68338832.0,73542831.0,1400.0,1400.0,1400.0,12.88,47.10,64000.0,34.95,0.0,...,0,0,0,0,0,1,0,0,0,0
17,68426831.0,73316657.0,11950.0,11950.0,11950.0,13.44,405.18,34000.0,10.20,0.0,...,0,0,0,0,0,1,0,0,0,0
18,66624733.0,71350547.0,18000.0,18000.0,18000.0,19.48,471.70,150000.0,9.39,0.0,...,0,0,0,0,0,1,0,0,0,0
19,68616873.0,73519699.0,8000.0,8000.0,8000.0,11.48,263.74,42000.0,34.80,0.0,...,0,0,0,0,0,1,0,0,0,0
20,67275481.0,72077199.0,20000.0,20000.0,20000.0,8.49,631.26,85000.0,17.61,1.0,...,0,0,0,0,0,1,0,0,0,0
21,68476668.0,73366513.0,20000.0,20000.0,20000.0,9.17,637.58,180000.0,14.67,0.0,...,1,0,0,0,0,1,0,0,0,0
22,68476702.0,73366548.0,28000.0,28000.0,28000.0,13.44,949.38,125000.0,7.49,0.0,...,0,0,0,0,0,1,0,0,0,0
23,68436666.0,73326493.0,5000.0,5000.0,5000.0,13.44,169.54,79000.0,12.70,0.0,...,0,0,0,0,0,1,0,0,0,0
24,68596180.0,73485987.0,20000.0,20000.0,20000.0,5.32,602.30,65000.0,18.83,0.0,...,0,0,0,0,0,1,0,0,0,0
25,67849662.0,72708407.0,4225.0,4225.0,4225.0,14.85,146.16,35000.0,15.22,2.0,...,0,0,0,0,0,1,0,0,0,0
26,68526883.0,73416719.0,15000.0,15000.0,15000.0,5.32,451.73,44000.0,15.34,0.0,...,0,0,0,0,0,1,0,0,0,0
27,68607141.0,73509983.0,17600.0,17600.0,17600.0,5.32,530.03,88000.0,26.59,0.0,...,1,0,0,0,0,1,0,0,0,0
28,68476715.0,73366561.0,6000.0,6000.0,6000.0,7.49,186.61,100000.0,13.28,1.0,...,0,0,0,0,0,1,0,0,0,0
29,67715283.0,72569997.0,16000.0,16000.0,16000.0,12.88,538.18,65000.0,18.96,0.0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421065,36631385.0,39374138.0,13000.0,13000.0,13000.0,8.19,408.52,85000.0,8.05,1.0,...,0,0,0,0,0,1,0,0,0,0
421066,36231083.0,38942474.0,15000.0,15000.0,15000.0,11.99,498.15,70000.0,8.47,0.0,...,0,0,0,0,0,1,0,0,0,0
421067,36691397.0,39434133.0,20000.0,20000.0,20000.0,6.99,617.46,72000.0,27.24,0.0,...,0,0,0,0,0,1,0,0,0,0
421068,36743377.0,39486112.0,4200.0,4200.0,4200.0,15.99,147.64,48000.0,36.93,0.0,...,0,0,0,0,0,1,0,0,0,0
421069,36331554.0,39042967.0,26950.0,26950.0,26950.0,8.19,846.88,54000.0,18.11,0.0,...,0,0,0,0,0,1,0,0,0,0
421070,36460697.0,39182359.0,23000.0,23000.0,23000.0,15.59,554.32,50000.0,31.95,0.0,...,0,0,0,0,0,1,0,0,0,0
421071,35773415.0,38468842.0,18700.0,18700.0,18700.0,17.86,473.44,52000.0,11.28,0.0,...,0,0,0,0,0,1,0,0,0,0
421072,36250801.0,38962184.0,6000.0,6000.0,6000.0,17.86,216.50,90000.0,2.84,0.0,...,0,0,0,0,0,1,0,0,0,0
421073,36371802.0,39103231.0,15000.0,15000.0,15000.0,11.44,329.44,57000.0,15.77,0.0,...,0,0,0,0,0,1,0,0,0,0
421074,36440728.0,39152101.0,25000.0,25000.0,25000.0,15.99,607.82,103000.0,5.27,0.0,...,0,0,0,0,0,1,0,0,0,0
421075,36361815.0,39093260.0,26500.0,26500.0,26500.0,8.67,545.87,92000.0,29.60,1.0,...,0,0,0,0,0,1,0,0,0,0
421076,35591131.0,38288343.0,25000.0,25000.0,25000.0,15.59,602.52,55000.0,5.52,0.0,...,0,0,0,0,0,1,0,0,0,0
421077,36201871.0,38913321.0,21000.0,21000.0,21000.0,6.03,639.15,65000.0,17.09,0.0,...,0,0,0,0,0,1,0,0,0,0
421078,36381756.0,39013193.0,8000.0,8000.0,8000.0,8.19,251.40,50000.0,17.62,0.0,...,0,0,0,0,0,1,0,0,0,0
421079,36231724.0,38943173.0,12000.0,12000.0,12000.0,9.49,384.34,40000.0,25.65,1.0,...,0,0,1,0,0,1,0,0,0,0
421080,36301729.0,39023153.0,10000.0,10000.0,10000.0,6.49,306.45,75000.0,33.66,0.0,...,0,0,0,0,0,1,0,0,0,0
421081,36250208.0,38961532.0,13150.0,13150.0,13150.0,14.99,312.77,30000.0,1.00,0.0,...,0,0,0,0,0,1,0,0,0,0
421082,36241316.0,38952731.0,6225.0,6225.0,6225.0,16.49,220.37,27000.0,18.58,0.0,...,0,0,0,0,0,1,0,0,0,0
421083,36231718.0,38943165.0,10775.0,10775.0,10775.0,6.03,327.95,54000.0,13.22,1.0,...,0,0,0,0,0,1,0,0,0,0
421084,36381704.0,39013139.0,7000.0,7000.0,7000.0,14.31,240.30,57000.0,16.80,2.0,...,0,0,0,0,0,1,0,0,0,0
421085,36421485.0,39142898.0,4000.0,4000.0,4000.0,8.67,126.59,50000.0,12.63,0.0,...,0,0,1,0,0,1,0,0,0,0
421086,35094480.0,37777829.0,7500.0,7500.0,7500.0,9.49,240.22,40000.0,25.63,0.0,...,0,0,0,0,0,1,0,0,0,0
421087,36260758.0,38972123.0,10850.0,10850.0,10850.0,19.24,399.04,32000.0,29.44,0.0,...,0,0,1,0,0,1,0,0,0,0
421088,36221446.0,38932858.0,11575.0,11575.0,11575.0,15.59,404.61,25400.0,27.08,0.0,...,1,0,0,0,0,1,0,0,0,0
421089,36330911.0,39042282.0,12000.0,12000.0,12000.0,11.99,398.52,63000.0,23.69,1.0,...,0,0,0,0,0,1,0,0,0,0
421090,36371250.0,39102635.0,10000.0,10000.0,10000.0,11.99,332.10,31000.0,28.69,0.0,...,0,0,0,0,0,1,0,0,0,0
421091,36441262.0,39152692.0,24000.0,24000.0,24000.0,11.99,797.03,79000.0,3.90,0.0,...,0,0,0,0,0,1,0,0,0,0
421092,36271333.0,38982739.0,13000.0,13000.0,13000.0,15.99,316.07,35000.0,30.90,0.0,...,0,0,0,0,0,1,0,0,0,0
421093,36490806.0,39222577.0,12000.0,12000.0,12000.0,19.99,317.86,64400.0,27.19,1.0,...,0,0,1,0,0,1,0,0,0,0
421094,36271262.0,38982659.0,20000.0,20000.0,20000.0,11.99,664.20,100000.0,10.83,0.0,...,0,0,0,0,0,1,0,0,0,0

In [15]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = loan15.drop('loan_status', 1)
Y = loan15['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

print(cross_val_score(rfc, X, Y, cv=10))

[0.97986274 0.98026644 0.98140628 0.98180998 0.97271432 0.97857991
 0.96214586 0.98062172 0.98005082 0.98059659]

In [16]:
from sklearn.decomposition import PCA

pca = PCA(n_components=4)
pca.fit(X)
PCA(copy=True, iterated_power='auto', n_components=4, random_state=None, svd_solver='auto', tol=0.0,
   whiten=False)
print(pca.explained_variance_ratio_)
X_reduced = pca.fit_transform(X)

cross_val_score(rfc, X_reduced, Y, cv=10)

[9.98422960e-01 1.22397239e-03 2.95771663e-04 2.43682199e-05]

array([0.68231578, 0.2113462 , 0.15955451, 0.15140937, 0.113346  ,
       0.09465685, 0.07259731, 0.07475837, 0.12966965, 0.24756567])

In [17]:
df = pd.DataFrame()
df['imp'] = rfc.fit(X, Y).feature_importances_
df['features'] = X.columns

In [18]:
df.sort_values(by='imp', ascending=False)

              imp                                       features
151  1.923585e-01                          last_pymnt_d_Jan-2017
24   1.398152e-01                                last_pymnt_amnt
15   1.026021e-01                                      out_prncp
166  6.976656e-02                          next_pymnt_d_Feb-2017
19   6.640059e-02                                total_rec_prncp
16   6.333789e-02                                  out_prncp_inv
18   5.185655e-02                                total_pymnt_inv
181  4.449761e-02                    last_credit_pull_d_Jan-2017
146  2.461605e-02                          last_pymnt_d_Dec-2016
22   1.958351e-02                                     recoveries
20   1.458008e-02                                  total_rec_int
193  1.375866e-02                    last_credit_pull_d_Oct-2016
17   1.338453e-02                                    total_pymnt
161  1.244365e-02                          last_pymnt_d_Nov-2016
167  1.143576e-02                          next_pymnt_d_Jan-2017
163  1.120628e-02                          last_pymnt_d_Oct-2016
165  1.087936e-02                          last_pymnt_d_Sep-2016
2    8.478408e-03                                      loan_amnt
6    7.743483e-03                                    installment
4    7.186435e-03                                funded_amnt_inv
23   6.600829e-03                        collection_recovery_fee
159  6.445346e-03                          last_pymnt_d_May-2016
153  6.318435e-03                          last_pymnt_d_Jul-2016
3    5.465845e-03                                    funded_amnt
155  4.251269e-03                          last_pymnt_d_Jun-2016
0    3.765480e-03                                             id
144  3.569066e-03                          last_pymnt_d_Aug-2016
1    2.875276e-03                                      member_id
5    2.610133e-03                                       int_rate
8    2.473038e-03                                            dti
..            ...                                            ...
141  1.846212e-06                          last_pymnt_d_Apr-2015
184  1.726169e-06                    last_credit_pull_d_Jun-2015
178  1.464373e-06                    last_credit_pull_d_Feb-2016
149  9.527472e-07                          last_pymnt_d_Jan-2015
190  8.379481e-07                    last_credit_pull_d_Nov-2015
125  3.766709e-07  title_New Baby and New House (CC Consolidate)
136  0.000000e+00                                  title_new day
135  0.000000e+00                              title_considerate
97   0.000000e+00                                   pymnt_plan_n
101  0.000000e+00                            purpose_educational
111  0.000000e+00                                purpose_wedding
114  0.000000e+00                  title_Credit Card/Auto Repair
117  0.000000e+00                                    title_DebtC
78   0.000000e+00                             home_ownership_ANY
121  0.000000e+00                    title_Learning and training
26   0.000000e+00                                    policy_code
127  0.000000e+00                       title_Pay off Lowes Card
188  0.000000e+00                    last_credit_pull_d_May-2015
128  0.000000e+00  title_Paying off higher interest cards & auto
168  0.000000e+00                          next_pymnt_d_Jul-2016
129  0.000000e+00      title_Prescription Drug and Medical Costs
138  0.000000e+00                                  title_odymeds
130  0.000000e+00                                     title_SAVE
137  0.000000e+00                   title_new kitchen for momma!
132  0.000000e+00                             title_Student Loan
133  0.000000e+00          title_Trying to come back to reality!
179  0.000000e+00                    last_credit_pull_d_Jan-2015
174  0.000000e+00                    last_credit_pull_d_Dec-2014
177  0.000000e+00                    last_credit_pull_d_Feb-2015
131  0.000000e+00  title_Simple Loan Until Contract Is Completed

[201 rows x 2 columns]

In [26]:
x = X.drop(['last_pymnt_d_Jan-2017', 'last_pymnt_amnt', 'out_prncp', 'next_pymnt_d_Feb-2017', 'total_rec_prncp','out_prncp_inv', 'total_pymnt_inv'], 1)

In [27]:
cross_val_score(rfc, x, Y, cv=10)

array([0.91396547, 0.93562252, 0.94654603, 0.94535869, 0.76627879,
       0.7840418 , 0.60884846, 0.85285806, 0.61141853, 0.56348264])